// Generated by https://quicktype.io

export interface Scenario {
    settings: Settings;
    title: string;
    tags: string[];
    _id: string;
    sections: Session[];
    __v: number;
}

export interface Question {
    title: string;
    _id: string;
}

export interface Session {
    title: string;
    questions?: Pick<Scenario, 'title' | '_id'>[];
    _id: string;
    id: string;
}

export interface Settings {
    public: boolean;
    shareQuestions: boolean;
}
